### ISSUE TITLE
Getting error fallbackfee

### ISSUE THREAD

**Issue by Goosie** [BlockchainCommons/Learning-Bitcoin-from-the-Command-Line#145]
When I follow the commands to create a simple transaction I get an error code -4

After doing txid=$(bitcoin-cli --testnet sendtoaddress 2NEnRNqYaCaHSaaipcCXKE6nBK4x9QG9oYT 0.001)

Fee estimation failed. Fallbackfee is disabled. Wait a few blocks or enable -fallbackfee.

How to get rid of this warning?

**Comment by shannona** [comment]
Added an explanation of the error: fundamentally, you shouldn't see it if you waited for your blockchain to sync and are using the standard bitcoin.conf.
