### ISSUE TITLE
Recreate btcblock alias using Blockstream Esplora REST API

### ISSUE THREAD

**Issue by 0xLeos** [BlockchainCommons/Learning-Bitcoin-from-the-Command-Line#148]
In _03_1_Verifying_Your_Bitcoin_Setup.md_, it's said about the difficulty in retrieving the current block height on testnet.
It's true, but at moment it can be done by the url https://blockstream.info/testnet/api/blocks/tip/height .

I have liked the command btcblock, used in the first version of that file.
Maybe the command can be recreated  just replacing the url as below:

``alias btcblock="echo \\\`bitcoin-cli getblockcount 2>&1\\\`/\\\`wget -O - https://blockstream.info/testnet/api/blocks/tip/height 2> /dev/null | cut -d : -f2 | rev | cut -c 2- | rev\\\`"``

**Comment by shannona** [comment]
Thanks! Looks like it's `cut -c 1-` not `2`, but with that change it's added!
