### ISSUE TITLE
Adding a link to run your own node on raspberry pi

### ISSUE THREAD

**Issue by keblek** [BlockchainCommons/Learning-Bitcoin-from-the-Command-Line#150]
This tutorial https://medium.com/@meeDamian/bitcoin-full-node-on-rbp3-revised-88bb7c8ef1d1

is actually quite good and can be followed to setup a full node on a raspberry pi or a crummy old laptop.

In section 2 can this be added as another alternative?

**Comment by shannona** [comment]
Thanks. Done.
