### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by keblek** [BlockchainCommons/Learning-Bitcoin-from-the-Command-Line#152]
in section 3.1 in run bitcoind 
this link is broken
https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/blob/master/02_1_Setting_Up_a_Bitcoin-Core_VPS_by_Hand.md

was it renamed?

**Comment by shannona** [comment]
Actually, it's a section that was removed entirely as the course involved. I've fixed it; thanks.
