### ISSUE TITLE
3.3: Setting Up Your Wallet - Think there is an error regarding Optional: Dump Your Wallet 

### ISSUE THREAD

**Issue by CandidateBlock** [BlockchainCommons/Learning-Bitcoin-from-the-Command-Line#179]
Hi,

I am following your course and find it very useful.

I maybe doing something wrong or misunderstanding but... 
in this chapter https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/blob/master/03_3_Setting_Up_Your_Wallet.md

You describe how to Dump your Wallet
$ bitcoin-cli backupwallet ~/backup.dat

and then restore with 

$ bitcoin-cli importwallet backup.dat

I think importwallet is expecting data from "Imports keys from a wallet dump file (see dumpwallet)"

so dumpwallet creates file for importwallet (I think)

backupwallet is used to create a full backup of wallet.dat file and to restore you overwrite (mv) the backup to the current and restart the bitcoind to read the updated wallet.dat

Could have this wrong.

Thanks

**Comment by shannona** [comment]
Right. That looks correct. Thank.
