### ISSUE TITLE
Bitcoin Commands appendix problems

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/Learning-Bitcoin-from-the-Command-Line#183]
Re: https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/blob/master/bitcoin-cli-commands-help.md

We should either write a script that formats all the output from current bitcoin help into a markdown page, and update it with new releases of bitcoin (as it is useful for this course and for searching for RPC commands within the course), or delete this page.

/cc @gorazdko @shannona

**Comment by shannona** [comment]
I've removed it; really was an artifact of v0.1 of the course.
