### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by nwmahoney** [BlockchainCommons/Learning-Bitcoin-from-the-Command-Line#186]
The `§2.1` link is broken in the [`Load the StackScript` section](https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/blob/master/02_1_Setting_Up_a_Bitcoin-Core_VPS_with_StackScript.md#load-the-stackscript) in `2.1: Setting Up a Bitcoin-Core VPS with Bitcoin Standup`. It points to https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/blob/master/02_1_Setting_Up_a_Bitcoin-Core_VPS_by_Hand.md, which gives a 404.

**Comment by shannona** [comment]
Thanks. That was a reference to a page that indeed no longer exists from the prior version of the text. (Resolved.)
