### ISSUE TITLE
Apparently, some of hwi.py's arguments and commands have changed

### ISSUE THREAD

**Issue by felipegontijo** [BlockchainCommons/Learning-Bitcoin-from-the-Command-Line#204]
When following along on [§7.3](https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/blob/master/07_3_Integrating_with_Hardware_Wallets.md), I have ran into some errors with `hwi.py` usage.

1. The alias suggested, which includes the `--testnet` argument, generates the following error for me when ran:
```
{"error": "hwi.py: error: unrecognized arguments: --testnet", "code": -2}
```
 - The help command `hwi -h` shows that the argument now takes the form of `--chain test`. I have performed this change and it worked.
 
 2. The `hwi -f $fingerprint getkeypool --wpkh 0 100` command generates the following error for me:
 ```
 {"error": "hwi.py: error: unrecognized arguments: --wpkh", "code": -2}
```
 - I removed `--wpkh` altogether, however maintaining `0 100`, and it worked. And the descriptor outputted is a P2WPKH type so I guess it is the standard now.
 
 I thought of opening a pull request, but figured I'd open an issue instead -- in case these errors were happening with me only.

**Comment by shannona** [comment]
Thanks! Another thing to flag for 2.1.
