### ISSUE TITLE
I want to translate for Portuguese.

### ISSUE THREAD

**Issue by KoreaComK** [BlockchainCommons/Learning-Bitcoin-from-the-Command-Line#223]
Hello,
I would like to contribute by translating the course to Portuguese.
I already have my CLA signed but I need write access to submit it in a PR.
Cheers.

**Comment by nyxnor** [comment]
You can send via mail, that is the other option.
Also, you dont need write option to submit a PR, just to be able to merge it.
Im writing at this moment the files names to portugues, to facilite reference, if you want to coniute reminaing the files following the same pattern, from item 30 and beyond would be helpful.

**Comment by shannona** [comment]
Terrific.

You should be able to submit via a branch and a PR. 

Once you're ready to go, I've already created the portuguese-translation branch. Just branch off of that for your work, and you can start working on the first chapter.

I wrote up much of the procedure here: https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/blob/master/TRANSLATING.md
If there are any questions, just let me know.

I also suggest using the files that I locked as the v2.01 release yesterday:
https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/releases/tag/v2.01

**Comment by KoreaComK** [comment]
@nyxnor and @shannona 
Thanks for the answer.
I will start right now!
Cheers!
