### ISSUE TITLE
My core says "Warning unknown new rules activated (versionbit 2) What do I need to do?

### ISSUE THREAD

**Issue by HippieHodler** [BlockchainCommons/Learning-Bitcoin-from-the-Command-Line#259]
Never done this before folks..

**Comment by HippieHodler** [comment]
![core](https://user-images.githubusercontent.com/78972033/124354451-0c42f400-dbda-11eb-9147-6de59f606c71.jpg)

**Comment by ndalliard** [comment]
everything is fine - you probably don't run bitcoin core version 21.1 were the taproot activation code was released

**Comment by HippieHodler** [comment]
Many thanks friend!!

**Comment by ndalliard** [comment]
how did you install the other version?

**Comment by HippieHodler** [comment]
Installed from windows 10 on an old PC @ndalliard Took forevah if you dig..

**Comment by HippieHodler** [comment]
For my configuration file I have it typed in as "server=1" as instructed by the guy on YouTube who teaches the proper way to download and setup for coldcard..

**Comment by ndalliard** [comment]
well then you just have to download the newer version of bitcoin core
