### ISSUE TITLE
07_3: Ethereum is no longer needed on Ledger

### ISSUE THREAD

**Issue by namcios** [BlockchainCommons/Learning-Bitcoin-from-the-Command-Line#306]
> 2. Go to the "Manager" and install "Bitcoin Test". The current version requires that you have "Bitcoin" and "Etereum" installed first.

As far as I have tested, it isn't currently necessary to have the Ethereum app installed on a Ledger in order to install Bitcoin Test.

**Comment by shannona** [comment]
Thanks!
