### ISSUE TITLE
Possible ambiguous script in chapter 11.2

### ISSUE THREAD

**Issue by csralvall** [BlockchainCommons/Learning-Bitcoin-from-the-Command-Line#419]
The following script is presented as `redeemScript` in line 80 of chapter 11.2:
```
OP_PUSHDATA (4 bytes) 0x9f7b2a5c OP_CHECKLOCKTIMEVERIFY OP_DROP OP_DUP OP_HASH160 OP_PUSHDATA (20 bytes) 0x371c20fb2e9899338ce5e99908e64fd30b789313 OP_EQUALVERIFY OP_CHECKSIG
```
I tried it with btcc removing the parenthesis thinking that it should be decoded without problem, but the following error is returned instead: `warning: opcode-like string was not an opcode: PUSHDATA`

That made me search for bitcoin opcodes and found the following resources:
- [bitcoin opcode reference](https://en.bitcoin.it/wiki/Script)
- [stackoverflow answer](https://bitcoin.stackexchange.com/questions/48534/op-pushdata1-is-not-allowed-inside-redeem-script-of-p2sh)

Taking that resources as reference, I can tell that OP_PUSHDATA is not an opcode and if the data is smaller than 75 bytes the proper way to build this redeem script to use it in a standard transaction is:
```
0x9f7b2a5c OP_CHECKLOCKTIMEVERIFY OP_DROP OP_DUP OP_HASH160 0x371c20fb2e9899338ce5e99908e64fd30b789313 OP_EQUALVERIFY OP_CHECKSIG
```
As line 88 of chapter 11.2 does.

Resulting in the following hexcode (using btcc):

**04**9f7b2a5cb17576a9**14**371c20fb2e9899338ce5e99908e64fd30b78931388ac

where 04 stands for the size of the first chunk of data and 14 (0x14) stands for the size of the second chunk of data.

**So the script in line 80 is pseudocode or it has an error?**

 If the former is the case, It would be helpful to make it explicit in the text.

**Comment by shannona** [comment]
Thanks for the resolution on this, closing out the issue too.
