### ISSUE TITLE
Typo "Nighteen" in Chapter One Introduction

### ISSUE THREAD

**Issue by Gilbog** [BlockchainCommons/Learning-Bitcoin-from-the-Command-Line#421]
In subsection 
https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/blob/master/01_0_Introduction.md#how-to-use-this-course
there is a typo in the following text passage

"If you are only interested in Lightning, zap over to Chapter Nighteen: Understanding Your Lightning Setup."

"Nighteen" should be "Nineteen"

**Comment by shannona** [comment]
Thanks, @csralvall was kind enough to get that one.
