### ISSUE TITLE
MAKE HOST MINGW PROCESS MISSING

### ISSUE THREAD

**Issue by Blazing-Mike** [BlockchainCommons/Learning-Bitcoin-from-the-Command-Line#467]
So I a total noob to bitcoin.... But I was confused in the appendix for installing Bitcoin from source... It's quite different from the Bitcoin documenting... There this step where you have to run a command for making the mingw cross compiler host in the depends directory... Is there something I'm missing... I've been trying to compile Bitcoin from source for days but I keep running into errors, but I should try the steps listed in the appendix.

**Comment by shannona** [comment]
Please, run through the steps in Appendix II on a Debian device, and if there are errors, report them.
