### ISSUE TITLE
./txfee-calc.sh: line 14: /usr/bin/bc: No such file or directory

### ISSUE THREAD

**Issue by Dimianovic** [BlockchainCommons/Learning-Bitcoin-from-the-Command-Line#536]
I just tried to use the transaction fee calculator. See [on the bottom of here](https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/blob/55ed2b0346bfaf25f226a029ef953b193bbbf62e/04_2__Interlude_Using_JQ.md) for reference.
I tried including in in the root and the standup directory, neither worked, I get the following error:  ```./txfee-calc.sh: line 14: /usr/bin/bc: No such file or directory```

There is indeed no ```/usr/bin/bc``` directory in the root directory. Can someone help me out here?

**Comment by shannona** [comment]
bc (basic calculator) is a standard program on the platforms that we suggest for the course (Debian, Mac). I would guess it's not available on your platform or in a different place. 

If it's not available to you, you can access the GNU version of it:
https://www.gnu.org/software/bc/
