### ISSUE TITLE
mintxfee still the way to go?

### ISSUE THREAD

**Issue by sjorsvanheuveln** [BlockchainCommons/Learning-Bitcoin-from-the-Command-Line#570]
4.1: Sending Coins the Easy Way

When I'm adding mintxfee=0.0001 to my bitcoinconf the transactions being sent out have much lower fees. So, apparently this is not really setting a minimal fee, or I don't understand it.

On stack I read that paytxfee is the way to go.
What's the situation here?

**Comment by shannona** [comment]
I can't say for sure without seeing the specific transactions and costs, but my guess would be that it's a misunderstanding for how `mintxfee` works. It sets the minimum fee *PER KB*. Today the [transaction sizes](https://bitcoinvisuals.com/chain-tx-size) ran between .19kB and .67kB for the majority of transactions, which means that the transaction fees would run between .000019 and .000067  BTC.

As far as I can see, this is still functional, but if you have an example of a transaction fee that doesn't match the `mintxfee`, let us know and we can recommend different methodology.
