### ISSUE TITLE
Multisig Real Estate example

### ISSUE THREAD

**Issue by sjorsvanheuveln** [BlockchainCommons/Learning-Bitcoin-from-the-Command-Line#571]
https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/blob/master/06_1_Sending_a_Transaction_to_a_Multisig.md

At the bottom of the page. Could somebody explain the real estate deal, because it doesn't seem to work from my point of view. The seller and agent could agree on not selling the house and claim the bitcoin, right? How does this work?

**Comment by shannona** [comment]
Yes. The presumption of an escrow agent is that they're an honest neutral party who is licensed/insured/etc.
