### ISSUE TITLE
06_3 Multisig address changed in example code

### ISSUE THREAD

**Issue by And1x** [BlockchainCommons/Learning-Bitcoin-from-the-Command-Line#573]
In the example code this [Multisig address](https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/blob/master/06_3_Sending_an_Automated_Multisig.md#create-the-multisig-address-everywhere) is created:
_tb1q9as46kupwcxancdx82gw65365svlzdwmjal4uxs23t3zz3rgg3wqpqlhex_
but later on the [next step](https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/blob/master/06_3_Sending_an_Automated_Multisig.md#watch-for-funds) another one is used:
_2Mzw7WBvh9RAQ4ssKqxyNyP7L9NAojLqSW8_
Is the example code inconsistent or am I missing something?

**Comment by shannona** [comment]
A lot of our examples have been done and redone over the years. So, this was inconsistent, probably because that one little section didn't get updated.

It's been fixed. Thank you!
