### ISSUE TITLE
Relevant Bitcoin Core 23.0 Changes

### ISSUE THREAD

**Issue by namcios** [BlockchainCommons/Learning-Bitcoin-from-the-Command-Line#575]
Flagging changes brought about by Bitcoin Core 23.0 released this week that are relevant for updating the course. Not an exhaustive list, so please comment additional ones found.

- Descriptor wallets are now the default. (Bring "Understanding the Descriptor" up in chapters to the know your setup part when the user creates and begins using a wallet?) (wallet RPC commands like `importmulti` and `dumpprivkey` cannot be used with descriptor wallets.)
- Taproot receiving addresses support for new descriptor wallets created
- Up to 2 typos on Bech32 addresses can now be spotted on the command line with `validateaddress` RPC method
- Freezing coins. (Opportunity for a "Coin Control" chapter to be added to the privacy section?)
- Support for CJDNS network
- Changes to fee estimation. (I know the course uses this but not sure if there needs to be updates on text as its back-end stuff.)
- Support For Tracepoints And Userspace, Statically-Defined Tracing.
- Both `createmultisig` and `addmultisigaddress` now include a warnings field, which will show a warning if a non-legacy address type is requested when using uncompressed public keys
- `listunspent` now includes `ancestorcount`, `ancestorsize`, and `ancestorfees` for each transaction output that is still in the mempool

**Comment by shannona** [comment]
Thanks much for pointers. I've written up a listing of all the things likely required to get LBTCftCL up to date:
https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/blob/master/TODO-23.md
