### ISSUE TITLE
How can i get the balance with cold address

### ISSUE THREAD

**Issue by sswink** [BlockchainCommons/Learning-Bitcoin-from-the-Command-Line#576]
I generate a address and i want to get its balance ;
> TestNet3Params params = TestNet3Params.get();   
>      ECKey key = new ECKey();  
 >       System.out.format("private key => ", key.getPrivateKeyAsHex()); 
  >      System.out.format("public key => ", key.getPublicKeyAsHex());  
   >     System.out.format("address => ", key.toAddress(params)); 

I run the following program to report an error

> BitcoindRpcClient rpcClient = new BitcoinJSONRPCClient("http://" + config.getUser() + ':' + config.getPassword() + "@" + config.getHost() + ":" + config.getPort()); 
> rpcClient.getBalance('mioddyp2c8Jk7XLCsT3971fVNacKvwfXJN')

**Comment by sswink** [comment]
I think the address is created offline rather than on the BTC node

**Comment by shannona** [comment]
The full hardware wallet details are here:
https://github.com/bitcoin/bitcoin/blob/22.x/doc/external-signer.md

I'm not aware of balance being supported.
