### ISSUE TITLE
Updating Linode + JQ documentation

### ISSUE THREAD

**Issue by tuckertranslator** [BlockchainCommons/Learning-Bitcoin-from-the-Command-Line#578]
Hi there,
It took me a while to get the JSON handling package, JQ, properly up and running on my Linode server. I am not an experienced SSH or CLI programmer, and the info offered in the tutorial did not get me far enough. I found this additional tutorial online to be really helpful, and was the solution that worked for me: https://www.zditect.com/code/javascript/using-jq-to-process-json-on-the-command-line-linode.html

It offers a few Linode-compatible solutions that can be executed from within the SSH console. This is the command I used: 
`sudo apt-get install jq` and it worked, no frills.

Thanks for the tutorial.

**Comment by shannona** [comment]
Thanks. We'll take a look to see if that's available now on our standard Debian setup.

**Comment by shannona** [comment]
Yep, looks great. I've updated the docs. Thanks!

**Comment by shannona** [comment]
Glad it's of use!
