### ISSUE TITLE
More explanation about CoinJoins needed

### ISSUE THREAD

**Issue by joegesualdo** [BlockchainCommons/Learning-Bitcoin-from-the-Command-Line#583]
# What
Add more explanation about CoinJoins

# Why
In section 7.2, [Using a Partially Signed Bitcoin Transaction](https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/blob/70f731609c2590ec21bb8ed47c1414f96a52408c/07_2_Using_a_Partially_Signed_Bitcoin_Transaction.md?plain=1#L579), it might be helpful to give a little more explanation on why CoinJoins exist, what problems they solve and what are some real world implementations.

# Note
I'd submit a pull request myself, but I'm not yet too familiar with how they work.

**Comment by shannona** [comment]
Thanks. It looks like we should add a "What is CoinJoin" information block.

**Comment by shannona** [comment]
Thanks for the feedback; there's now an infoblock.

https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/blob/master/07_2_Using_a_Partially_Signed_Bitcoin_Transaction.md#use-a-psbt-to-coinjoin

**Comment by joegesualdo** [comment]
Awesome! Thanks @shannona!
